server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: config-center-8000
    prefer-ip-address: true

spring:
  application:
    name: config-center-8000
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/anarchy582/renthouse-config-center
          username: 15889951171
          password: wei13422099036
          default-label: master

